apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodordering
  labels:
    app: foodordering
spec:
  replicas: 1
  template:
    metadata:
      name: foodordering
      labels:
        app: foodordering
    spec:
      containers:
        - name: foodordering
          image: ruanxingke/foodordering
          ports:
            - containerPort: 8081
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: service-api-key
            - name: "PORT"
              value: "8081"
            - name: "DATABASE_HOST"
              value: "mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: foodordering
---
apiVersion: v1
kind: Service
metadata:
  name: foodordering-service
spec:
  selector:
    app: foodordering
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

