apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ruanxingke/gateway
          ports:
            - containerPort: 9999
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: service-api-key
            - name: "PORT"
              value: "9999"
  selector:
    matchLabels:
      app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30005
  type: NodePort