server:
  port: ${PORT:9999}

zuul:
  routes:
    testabc:
      serviceId: test
      path: /testabc/**
    api-foodordering:
      path: /api-foodordering/**
      url: http://foodordering-service:8081/
    api-orderdish:
      path: /api-orderdish/**
      url: http://orderdish-service:8082/

auth-url: http://ea-auth-service:8888

exclude-routes:
  urls: /api-foodordering,/api-orderdish/

api:
  key: ${API-KEY}

spring:
  zipkin:
    # zipkin服务端地址
    base-url: http://zipkin
  sleuth:
    sampler:
      # 采集频率 1.0表示100%采集
      percentage: 1.0